### ISSUE TITLE
Performance issues due to synchronous behavior of lock_door

### ISSUE THREAD

**Issue by ofilmstrom** [seamapi/php#174]
The following small piece of code indicates that using php functions for lock_door (in this example) have some performance challenges (same outcome with unlock_door):

$ts=hrtime(true); //DEBUG
/* .... */
/* Some code here to setup API and determine the device_id */
/* .... */

/* Lock action detected */
		if ($action=="lock") {
			echo "Entering call to Seam lock_door: ".(hrtime(true)-$ts)/1e+9."s<br>"; //DEBUG
			$apiResult=$seam->locks->lock_door($all_locks[$lockid]->device_id);
			echo "Call to Seam lock_door exited: ".(hrtime(true)-$ts)/1e+9."s<br>"; //DEBUG
		        print_r($apiResult);  //DEBUG
		    }

The typical output from this:

Entering call to Seam lock_door: 0.306582973s
Call to Seam lock_door exited: 22.555832658s
Seam\Objects\ActionAttempt Object ( [action_attempt_id] => bcc30ca3-7ccb-41ba-ae97-cb299e8a29ba [action_type] => LOCK_DOOR [error] => [result] => stdClass Object ( ) [status] => success )

Seems that the **lock_door function takes about 22 seconds** to execute.
The physical lock is locked correctly but the call to lock_door seems to be synchronous and is blocking further execution and handling of ActionAttempt for example.

API version v2.23.0
Running php version 8.3.4

**Comment by razor-x** [comment]
Hi @ofilmstrom. This delay is likely because `lock_door` method waits for the action attempt to complete before continuing (waits for the door to unlock or the attempt to fail or timeout).

Can you try passing `wait_for_action_attempt=false` to that method call? This means the function should return very quickly, but the action attempt will be pending, so your application will need to decide how to handle the pending action attempt.

**Comment by ofilmstrom** [comment]
Thank you @razor-x. This was clearly the problem. For some reason I assumed this would be the default, but now reading the source code I realize  that it is not. Have now tested with this call  instead as suggested

$apiResult=$seam->locks->lock_door($all_locks[$lockid]->device_id,null,false);

with the outcome

Entering call to Seam lock_door: 0.311606116s
Call to Seam lock_door exited: 0.723505244s

So I close this now as it now works as expected
