### ISSUE TITLE
V1 TODOs

### ISSUE THREAD

**Issue by seveibar** [seamapi/php#2]
List of params to add support for:
- [x] `device->get` - `name`
- [x] `device->list` - `connected_account_id`, `connect_webview_id`, `device_type`
- [x] `workspaces->get` - `workspace_id`
- [x] `workspaces->list` - `workspace_id`
- [x] `access_codes->get` - `device_id`
- [x] `connect_webviews->create` - `device_selection_mode`
- [x] `locks->get` - `name`
- [x] `locks->list` - `connect_webview_id`

**Comment by andrii-balitskyi** [comment]
Missing methods:
- [ ] `workspaces.poll_until_ready`
- [ ] `access_codes.update`
- [ ] `access_codes.delete`
